import { createUploadPolicy } from './upload-policy'

const GEMINI_FILE_SEARCH_SUPPORTED_MIME_TYPES = [
  'application/dart',
  'application/ecmascript',
  'application/json',
  'application/msword',
  'application/pdf',
  'application/sql',
  'application/typescript',
  'application/vnd.jupyter',
  'application/vnd.ms-excel',
  'application/vnd.oasis.opendocument.text',
  'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
  'application/vnd.openxmlformats-officedocument.wordprocessingml.template',
  'application/vnd.openxmlformats-officedocument.presentationml.presentation',
  'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
  'application/x-csh',
  'application/x-hwp',
  'application/x-hwp-v5',
  'application/x-latex',
  'application/x-php',
  'application/x-powershell',
  'application/x-sh',
  'application/x-shellscript',
  'application/x-tex',
  'application/x-zsh',
  'application/xml',
  'application/zip',
  'text/plain',
  'text/markdown',
  'text/html',
  'text/css',
  'text/csv',
  'text/jsx',
  'text/xml',
  'text/rtf',
  'text/tab-separated-values',
  'text/tsv',
  'text/tsx',
  'text/x-python',
  'text/x-python-script',
  'text/x-script.python',
  'text/x-c',
  'text/x-c++hdr',
  'text/x-c++src',
  'text/x-chdr',
  'text/x-csharp',
  'text/x-go',
  'text/x-haskell',
  'text/x-java',
  'text/x-java-properties',
  'text/x-java-source',
  'text/x-kotlin',
  'text/x-lua',
  'text/x-perl',
  'text/x-rst',
  'text/x-ruby-script',
  'text/x-rust',
  'text/x-sass',
  'text/x-scala',
  'text/x-scss',
  'text/x-sh',
  'text/x-sql',
  'text/x-swift',
  'text/x-tcl',
  'text/x-tex',
  'text/x-vbasic',
  'text/x-bibtex',
  'text/javascript',
  'text/yaml',
  'text/vnd.wap.wmlscript',
] as const

const GEMINI_FILE_SEARCH_EXTENSION_TO_MIME_TYPE = {
  '.bib': 'text/x-bibtex',
  '.c': 'text/x-c',
  '.cc': 'text/x-c++src',
  '.cpp': 'text/x-c++src',
  '.cs': 'text/x-csharp',
  '.csh': 'application/x-csh',
  '.css': 'text/css',
  '.csv': 'text/csv',
  '.cxx': 'text/x-c++src',
  '.dart': 'application/dart',
  '.doc': 'application/msword',
  '.docx':
    'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
  '.go': 'text/x-go',
  '.h': 'text/x-chdr',
  '.hpp': 'text/x-c++hdr',
  '.hs': 'text/x-haskell',
  '.htm': 'text/html',
  '.html': 'text/html',
  '.hwp': 'application/x-hwp',
  '.ipynb': 'application/vnd.jupyter',
  '.java': 'text/x-java-source',
  '.js': 'text/javascript',
  '.json': 'application/json',
  '.jsx': 'text/jsx',
  '.kt': 'text/x-kotlin',
  '.kts': 'text/x-kotlin',
  '.latex': 'application/x-latex',
  '.lua': 'text/x-lua',
  '.md': 'text/markdown',
  '.markdown': 'text/markdown',
  '.mjs': 'application/ecmascript',
  '.odt': 'application/vnd.oasis.opendocument.text',
  '.pdf': 'application/pdf',
  '.php': 'application/x-php',
  '.pl': 'text/x-perl',
  '.pptx':
    'application/vnd.openxmlformats-officedocument.presentationml.presentation',
  '.properties': 'text/x-java-properties',
  '.ps1': 'application/x-powershell',
  '.py': 'text/x-python',
  '.rb': 'text/x-ruby-script',
  '.rst': 'text/x-rst',
  '.rtf': 'text/rtf',
  '.rs': 'text/x-rust',
  '.sass': 'text/x-sass',
  '.scala': 'text/x-scala',
  '.scss': 'text/x-scss',
  '.sh': 'application/x-shellscript',
  '.sql': 'application/sql',
  '.swift': 'text/x-swift',
  '.tcl': 'text/x-tcl',
  '.tex': 'application/x-tex',
  '.ts': 'application/typescript',
  '.tsv': 'text/tsv',
  '.tsx': 'text/tsx',
  '.txt': 'text/plain',
  '.vbs': 'text/x-vbasic',
  '.wmls': 'text/vnd.wap.wmlscript',
  '.xls': 'application/vnd.ms-excel',
  '.xlsx':
    'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
  '.xml': 'application/xml',
  '.yaml': 'text/yaml',
  '.yml': 'text/yaml',
  '.zip': 'application/zip',
  '.zsh': 'application/x-zsh',
} as const

const GEMINI_FILE_SEARCH_FILE_NAMES_TO_MIME_TYPE = {
  dockerfile: 'text/plain',
} as const

const GEMINI_FILE_SEARCH_MAX_FILE_SIZE_BYTES = 100 * 1024 * 1024

export const geminiFileSearchUploadPolicy = createUploadPolicy({
  id: 'gemini-file-search',
  displayName: 'Gemini File Search',
  supportedMimeTypes: GEMINI_FILE_SEARCH_SUPPORTED_MIME_TYPES,
  extensionToMimeType: GEMINI_FILE_SEARCH_EXTENSION_TO_MIME_TYPE,
  fileNameToMimeType: GEMINI_FILE_SEARCH_FILE_NAMES_TO_MIME_TYPE,
  maxFileSizeBytes: GEMINI_FILE_SEARCH_MAX_FILE_SIZE_BYTES,
})
