/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StoresStoreIdRouteImport } from './routes/stores/$storeId'
import { Route as StoresStoreIdIndexRouteImport } from './routes/stores/$storeId/index'
import { Route as StoresStoreIdDocumentsDocumentIdRouteImport } from './routes/stores/$storeId/documents/$documentId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoresStoreIdRoute = StoresStoreIdRouteImport.update({
  id: '/stores/$storeId',
  path: '/stores/$storeId',
  getParentRoute: () => rootRouteImport,
} as any)
const StoresStoreIdIndexRoute = StoresStoreIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StoresStoreIdRoute,
} as any)
const StoresStoreIdDocumentsDocumentIdRoute =
  StoresStoreIdDocumentsDocumentIdRouteImport.update({
    id: '/documents/$documentId',
    path: '/documents/$documentId',
    getParentRoute: () => StoresStoreIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/stores/$storeId': typeof StoresStoreIdRouteWithChildren
  '/stores/$storeId/': typeof StoresStoreIdIndexRoute
  '/stores/$storeId/documents/$documentId': typeof StoresStoreIdDocumentsDocumentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/stores/$storeId': typeof StoresStoreIdIndexRoute
  '/stores/$storeId/documents/$documentId': typeof StoresStoreIdDocumentsDocumentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/stores/$storeId': typeof StoresStoreIdRouteWithChildren
  '/stores/$storeId/': typeof StoresStoreIdIndexRoute
  '/stores/$storeId/documents/$documentId': typeof StoresStoreIdDocumentsDocumentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/stores/$storeId'
    | '/stores/$storeId/'
    | '/stores/$storeId/documents/$documentId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/stores/$storeId' | '/stores/$storeId/documents/$documentId'
  id:
    | '__root__'
    | '/'
    | '/stores/$storeId'
    | '/stores/$storeId/'
    | '/stores/$storeId/documents/$documentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  StoresStoreIdRoute: typeof StoresStoreIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stores/$storeId': {
      id: '/stores/$storeId'
      path: '/stores/$storeId'
      fullPath: '/stores/$storeId'
      preLoaderRoute: typeof StoresStoreIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stores/$storeId/': {
      id: '/stores/$storeId/'
      path: '/'
      fullPath: '/stores/$storeId/'
      preLoaderRoute: typeof StoresStoreIdIndexRouteImport
      parentRoute: typeof StoresStoreIdRoute
    }
    '/stores/$storeId/documents/$documentId': {
      id: '/stores/$storeId/documents/$documentId'
      path: '/documents/$documentId'
      fullPath: '/stores/$storeId/documents/$documentId'
      preLoaderRoute: typeof StoresStoreIdDocumentsDocumentIdRouteImport
      parentRoute: typeof StoresStoreIdRoute
    }
  }
}

interface StoresStoreIdRouteChildren {
  StoresStoreIdIndexRoute: typeof StoresStoreIdIndexRoute
  StoresStoreIdDocumentsDocumentIdRoute: typeof StoresStoreIdDocumentsDocumentIdRoute
}

const StoresStoreIdRouteChildren: StoresStoreIdRouteChildren = {
  StoresStoreIdIndexRoute: StoresStoreIdIndexRoute,
  StoresStoreIdDocumentsDocumentIdRoute: StoresStoreIdDocumentsDocumentIdRoute,
}

const StoresStoreIdRouteWithChildren = StoresStoreIdRoute._addFileChildren(
  StoresStoreIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  StoresStoreIdRoute: StoresStoreIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
